# Generated by Django 5.2.7 on 2025-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
