# Generated by Django 5.2.7 on 2025-10-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_cryptocurrency_market_cap_cryptocurrency_volume_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='realized_gain_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Realized gain or loss from this trade (0 for BUY, calculated for SELL). Future extension: fees/commissions.', max_digits=20, null=True),
        ),
    ]
