# Generated by Django 5.2.7 on 2025-10-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_transaction_realized_gain_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='category',
            field=models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('STABLECOIN', 'Stablecoin'), ('DEFI', 'DeFi'), ('NFT', 'NFT'), ('MEME', 'Meme')], db_index=True, default='CRYPTO', help_text='Category of cryptocurrency for filtering and organization', max_length=20),
        ),
    ]
