# Generated by Django 5.2.7 on 2025-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_category_to_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='yfinance_symbol',
            field=models.CharField(blank=True, help_text='Yahoo Finance ticker symbol (e.g., BTC-USD)', max_length=20, null=True),
        ),
    ]
