# Generated by Django 5.2.7 on 2025-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_cryptocurrency_yfinance_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, help_text='11-digit account number', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Joint'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', help_text='Type of account', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
